### ISSUE TITLE
Installation/update takes a long time

### ISSUE THREAD

**Issue by SeanDS** [adamsilverstein/mathml-block#12]
[As reported on WordPress.org](https://wordpress.org/support/topic/unzipping-plugin-takes-a-long-time/), the plugin zip file contains many thousands of files because of the MathJax fonts, and therefore takes a long time to unzip on the server, and the user is left wondering if the plugin is actually installing or if something has gone wrong. In my case I waited for at least 5 minutes before it installed. It installed version 1.0.0 for some reason, even though the directory shows 1.1.0. When trying to update it in the plugin page, it again waits many minutes, says it has successfully updated, but actually hasn't - refreshing the page I again see version 1.0.0.

I wonder if the huge number of files in the zip has broken the WordPress directory's zip code. In any case, is there some way to reduce the number of fonts bundled in the plugin to reduce installation/update times?

**Comment by adamsilverstein** [comment]
@SeanDS thanks for the feedback.

I'll take a look at reducing this - I noticed the issue as well. 

Originally I wasn't bundling MathJax at all, instead linking to the official CDN (https://github.com/adamsilverstein/mathml-block/commit/5456d577bb116fb8be37bf8afefdde1318f8c8fc#diff-76f8b02ecd70638524f0a2ba1131148cR23) to load the MathJax library (which is what mathjax reccomends and  included loading all the bundled fonts) - however my plugin was rejected from the .org repository because of this rule: https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#8-plugins-may-not-send-executable-code-via-third-party-systems

perhaps we can load the mathjax library in the plugin, while still loading the font files from the CDN (which is explicitly allowed under the plugin policies). I'll look into it.

**Comment by adamsilverstein** [comment]
@SeanDS I switched things around to using the CDN script, greatly reducing the plugin size. Can you try upgrading again?

**Comment by adamsilverstein** [comment]
Closing as resolved.
